---
title: "EM Testing"
author: "Kushal Shah"
date: "4/23/2018"
output: html_document
---

```{r}
pairs(diabetes,col=diabetes$class)
par(xpd = TRUE)
legend("bottomright", fill = unique(diabetes$class), legend = c( levels(diabetes$class)))
```
```{r}
hist(diabetes$glucose,breaks=50)
hist(diabetes$insulin,breaks=50)
hist(diabetes$sspg,breaks=50)
```

```{r}
gmm.glucose <- normalmixEM(diabetes$glucose, lambda = c(.125,.8,.075), mu = c(50,100,150), sigma = c(20,10,50),maxit=2000,epsilon=.01)
summary(gmm.glucose)
plot(gmm.glucose, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="Glucose Levels", xlab2="Glucose",breaks=25)
```

```{r}
gmm.insulin <- normalmixEM(diabetes$insulin, lambda = c(1,1,1), mu = c(350,500,1000), sigma = c(60,100,300),maxit=2000,epsilon=.01)
summary(gmm.insulin)
plot(gmm.insulin, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="Insulin Levels", xlab2="Insulin",breaks=25)
```

```{r}
gmm.sspg <- normalmixEM(diabetes$sspg, lambda = c(.8,.15,.05), mu = c(130,270,500), sigma = c(70,20,200),maxit=2000,epsilon=.01)
summary(gmm.sspg)
plot(gmm.sspg, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="SSPG Levels", xlab2="SSPG",breaks=27)
```


```{r}
gmm.sspg <- normalmixEM(diabetes$sspg, lambda = c(1,1,1), mu = c(350,800,1200), sigma = c(60,200,300),maxit=2000)
summary(gmm.sspg)
```


```{r}
pairs(iris,col=iris$Species,cex=.7)
par(xpd = TRUE)
legend("bottomright", fill = unique(iris$Species), legend = c( levels(iris$Species)))
```

```{r}
banknote <- read.csv('http://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt', header=FALSE)

names(banknote) <- c("variance","skewness","kurtosis","entropy","authenticity")
banknote$authenticity <- as.factor(banknote$authenticity)
```

```{r}
pairs(banknote,panel=panel.smooth,col=banknote$authenticity,cex=.4)
par(xpd = TRUE)
legend("bottomright", fill = unique(banknote$authenticity), legend = c( levels(banknote$authenticity)))
```

```{r}
hist(banknote$variance,breaks=50) # 4 classes
hist(banknote$skewness,breaks=50) # 5 classes
hist(banknote$kurtosis,breaks=50) # 3 classes
hist(banknote$entropy,breaks=50) # 2 classes
```


```{r}
gmm.variance <- normalmixEM(banknote$variance, lambda = c(1,1,1,1), mu = c(-4,-2,0,4), sigma = c(1.5,1,1,0.5),maxit=2000,epsilon=.01)
summary(gmm.variance)
plot(gmm.variance, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="Variance Levels", xlab2="Variance",breaks=25)
```

```{r}
gmm.skewness <- normalmixEM(banknote$skewness, lambda = c(.05,.2,.25,.2,.3), mu = c(-13,-7,0,3,8), sigma = c(1,2,1.5,1.5,3),maxit=2000,epsilon=.01)
summary(gmm.skewness)
plot(gmm.skewness, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="Skewness Levels", xlab2="Skewness",breaks=25)
```

```{r}
gmm.kurtosis <- normalmixEM(banknote$kurtosis, lambda = c(.2,.6,.2), mu = c(-4,0,6), sigma = c(2,2,3),maxit=2000,epsilon=.01)
summary(gmm.kurtosis)
plot(gmm.kurtosis, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="Kurtosis Levels", xlab2="Kurtosis",breaks=25)
```

```{r}
gmm.entropy <- normalmixEM(banknote$entropy, lambda = c(.3,.7), mu = c(-4,0), sigma = c(2,1),maxit=2000,epsilon=.01)
summary(gmm.entropy)
plot(gmm.entropy, density=TRUE, cex.axis=1.4, cex.lab=1.4, cex.main=1.8,main2="Entropy Levels", xlab2="Entropy",breaks=25)
```