---
title: "Exploring different prior choices for the expectation-maximization algorithm."
author: "Damon Pham, Kushal Shah, Ethan Violette"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
#source("https://bioconductor.org/biocLite.R")
#biocLite("biomaRt")
#biocLite("rhdf5")
#biocLite("UniProt.ws")
#devtools::install_github("cmap/cmapR")

list.of.packages <- c('kableExtra', 'knitr', 'ggplot2','gridExtra','reshape2','grid')
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages, require, character.only = TRUE)
rm(list.of.packages, new.packages)

opts_chunk$set(echo=FALSE, cache=TRUE, autodep=TRUE,
               message=FALSE, warning=FALSE,
               fig.align="center")

source('scripts.R')
```

# Synthetic dataset #1: Univariate case

For the first dataset, we created 1000 observations sampled from:

* Normal(0, 1) with 50% chance
* Normal(10, 8) with 30% chance
* Normal(-20, 3) with 20% chance

```{r}
set.seed(0)
x = generate_mog(n_data=1000, means=c(0,10,-20), sds=c(1,8,3), priors=c(.5,.3,.2))
hist(x, breaks=100)

#
```